In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('survey_results_public.csv')

In [3]:
schema_df = pd.read_csv('survey_results_schema.csv')

In [4]:
df.sort_values(by='Country')  # inplace=True to keep the changes

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
37431,37432,I am a student who is learning to code,"Student, part-time",Afghanistan,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Younger than 5 years,Books / Physical media,NaN,...,Under 18 years old,"Or, in your own words:","Or, in your own words:",Straight / Heterosexual;Bisexual;Prefer to sel...,White or of European descent;I don't know;Mult...,"Or, in your own words:","Or, in your own words:",Too long,Difficult,NaN
11461,11462,I am a developer by profession,"Not employed, but looking for work",Afghanistan,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,Middle Eastern,None of the above,None of the above,Appropriate in length,Easy,NaN
67130,67131,I am a developer by profession,NaN,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62970,62971,"I am not primarily a developer, but I write co...","Not employed, but looking for work",Afghanistan,NaN,NaN,Some college/university study without earning ...,18 - 24 years,Books / Physical media,6,...,25-34 years old,Man,No,Straight / Heterosexual,Multiracial;Indigenous (such as Native America...,None of the above,None of the above,Too long,Difficult,NaN
14882,14883,I am a developer by profession,Employed full-time,Afghanistan,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,8,...,25-34 years old,Man,No,NaN,South Asian,None of the above,None of the above,Appropriate in length,Easy,4200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13194,13195,I am a developer by profession,Employed full-time,Zimbabwe,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",18,...,35-44 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Too long,Easy,NaN
80996,80997,I code primarily as a hobby,"Not employed, and not looking for work",Zimbabwe,NaN,NaN,Primary/elementary school,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",Less than 1 year,...,Under 18 years old,Man,No,Straight / Heterosexual,Black or of African descent,I am blind / have difficulty seeing,None of the above,Appropriate in length,Easy,NaN
73741,73742,I am a developer by profession,"Student, part-time",Zimbabwe,NaN,NaN,Some college/university study without earning ...,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",5,...,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
73192,73193,I am a developer by profession,Employed full-time,Zimbabwe,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",5,...,25-34 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,2400.0
38428,38429,I am a developer by profession,Employed full-time,Zimbabwe,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",5 - 10 years,Coding Bootcamp;Other online resources (ex: vi...,10,...,25-34 years old,Woman,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN

In [5]:
df['Country'].head(50)  # it gives us the first 50 countries sorted

0                                              Slovakia
1                                           Netherlands
2                                    Russian Federation
3                                               Austria
4     United Kingdom of Great Britain and Northern I...
5                              United States of America
6                              United States of America
7                                              Malaysia
8                                                 India
9                                                Sweden
10    United Kingdom of Great Britain and Northern I...
11                                                Spain
12                                              Germany
13                                                 Peru
14    United Kingdom of Great Britain and Northern I...
15                             United States of America
16                                               Turkey
17                                               Canada
18                                            Singapore
19                                               Brazil
20                                              Germany
21                                               Sweden
22                                                India
23                                               France
24                                              Germany
25                                              Germany
26                                          Switzerland
27    United Kingdom of Great Britain and Northern I...
28    United Kingdom of Great Britain and Northern I...
29                                   Russian Federation
30                                               Malawi
31                                               Israel
32                                               Poland
33                                               Turkey
34                                              Ukraine
35                                              Germany
36                             United States of America
37                             United States of America
38                                             Viet Nam
39                                                India
40                                             Portugal
41                                               France
42                                                Italy
43    United Kingdom of Great Britain and Northern I...
44                                               France
45                                               Brazil
46                                                 Peru
47                             United States of America
48                                             Bulgaria
49                                                India
Name: Country, dtype: object

In [7]:
#df[['Country', 'ConvertedComp']].head(50)
# it gives us the first 50 countries sorted and their salaries

In [9]:
#df.sort_values(by=['Country', 'ConvertedComp'], ascending=[True, False], inplace=False)
# here we print country and salaries byt salaries are descending

In [11]:
#df['ConvertedComp'].nlargest(10)
# here we want to see the ten highest salaries of the survey

In [14]:
#df.nlargest(10, 'ConvertedComp')
# it will show us all the survey results instead of the previous example with only one column(or more)
# the opposite method is .nsmallest()